### ISSUE TITLE
Meetup 13 de agosto 2015

### ISSUE THREAD

**Issue by san650** [ember-montevideo/meetups#1]
http://www.meetup.com/ember-montevideo/events/223890879/
# Meetup check list
## Antes del meetup
- [x] Armar agenda y actividades
- [x] Avisar a Sebamar y Valeria qué día es el meetup para reservar el lugar
- [x] Avisar a WyeWorks que ese día se va a realizar el meetup a las 19:30
- [x] Avisar por Slack de Ember Montevideo
- [x] Avisar por Slack de Open Web Uruguay
- [x] Mandar tweet con la cuenta del meetup
- [x] Mandar tweet con la cuenta personal (santiago)
- [x] Actualizar página de meetup con la agenda
- [x] Mirar si las mesas de la cocina se pueden desarmar para moverlas al living
## Día del meetup
- [x] Enfriar bebidas
- [x] Avisar al portero que viene gente al Meetup
- [x] Comprar bebida
- [x] Comprar snacks
- [x] Comprar cena para que llegue a la hora deseada (22:00)
- [x] Hoja A4 con la contraseña de la WiFi
- [x] Arreglar living con mesas del comedor
- [ ] Regalar algunos stickers
- [ ] Invitar a las personas al canal de slack
- [x] Sacar fotos!
- [x] Alargues
- [x] Agradecer a los sponsors
## Después del meetup
- [x] Escribir lo que se hizo y subirlo al github de ember montevideo
- [x] Mandar tweet con foto y agradeciendo a los que vinieron
- [x] Pasar las facturas a Carri

**Comment by san650** [comment]
:pray: gracias @juanazam por ayudar a organizar el meetup!

**Comment by juanazam** [comment]
a las ordenes @san650, cuando gustes!
