### ISSUE TITLE
Meetup 8 de octubre 2015

### ISSUE THREAD

**Issue by san650** [ember-montevideo/meetups#3]
http://www.meetup.com/ember-montevideo/events/224664352/
# Meetup check list
## Antes del meetup
- [ ] Preparar la agenda y actividades
- [x] Confirmar que no haya otros eventos ese día: feriados, paros, partidos, etc.
- [x] Avisar a Sebamar y Valeria qué día es el meetup para reservar el lugar
- [x] Avisar a WyeWorks que ese día se va a realizar el meetup a las 19:30
- [x] Avisar por Slack de Ember Montevideo
- [x] Avisar por Slack de Open Web Uruguay
- [x] Mandar tweet con la cuenta del meetup
- [x] Mandar tweet con la cuenta personal (santiago)
- [ ] Actualizar página de meetup con la agenda
- [x] Mirar si las mesas de la cocina se pueden desarmar para moverlas al living
## Día del meetup
- [ ] Enfriar bebidas
- [ ] Avisar al portero que viene gente a la reunión
- [ ] Comprar bebida
- [ ] Comprar snacks
- [ ] Comprar cena para que llegue a la hora del cierre (22:00)
- [ ] Hoja A4 con la contraseña de la WiFi
- [ ] Arreglar living con mesas del comedor
- [ ] Regalar algunos stickers
- [ ] Invitar a las personas al canal de slack
- [ ] Sacar fotos
- [ ] Alargues
- [ ] Agradecer a los sponsors
## Después del meetup
- [x] Escribir lo que se hizo y subirlo a GitHub
- [x] Mandar tweet con foto y agradeciendo a los que vinieron
- [x] Pasar las facturas al Carri

**Comment by san650** [comment]
@xymbol @jmbejar acá queda el check list que hemos usado en los últimos meetups, les puede servir para coordinar mas fácil la organización.

**Comment by jmbejar** [comment]
@san650 Buenísimo!

**Comment by san650** [comment]
Done!
